PROCESS_TYPED_DESCRIPTOR(UAV, RWTexture2D, float4, 1);
PROCESS_TYPED_DESCRIPTOR(UAV, RWTexture3D, float4, 2);
PROCESS_UNTYPED_DESCRIPTOR(SRV, Texture2D, 1);
PROCESS_UNTYPED_DESCRIPTOR(SRV, Texture3D, 2);
PROCESS_UNTYPED_DESCRIPTOR(SAMPLER, SamplerState, 1);