PROCESS_TYPED_DESCRIPTOR(UAV, 1, RWTexture2D, float4);
PROCESS_TYPED_DESCRIPTOR(UAV, 2, RWTexture3D, float4);
PROCESS_UNTYPED_DESCRIPTOR(SRV, 1, Texture2D);
PROCESS_UNTYPED_DESCRIPTOR(SRV, 2, Texture3D);
PROCESS_SAMPLER_DESCRIPTOR(1, SamplerState);