TYPED_DESCRIPTOR(UAV, 1, RWTexture2D, float4);
TYPED_DESCRIPTOR(UAV, 2, RWTexture3D, float4);
UNTYPED_DESCRIPTOR(SRV, 1, Texture2D);
UNTYPED_DESCRIPTOR(SRV, 2, Texture3D);
SAMPLER_DESCRIPTOR(1, SamplerState);